find . -maxdepth 2 -name run.t |
while read run
do
  DIR=`dirname $run`
  TEST=`basename $DIR`
  TEST=${TEST%.t}
  echo "Setup $TEST"
  cd $DIR
  rm -f flags
  ln -s ../../flags .

  cat > dune-project <<-EOF
	(lang dune 3.21)
	(using rocq 0.11)
	;; DO NOT MODIFY. Generated by ../setup-tests.sh
EOF
  cat > dune <<-EOF
	;; DO NOT MODIFY. Generated by ../setup-tests.sh

	(env
	  (_
	    (flags :standard %{read-lines:flags/ocamlc})
	    (ocamlopt_flags :standard -O3 -unbox-closures)
	    (rocq
	     (rocqdep_flags :standard -w +all)
	     (flags (:standard %{read-lines:flags/coqc})))))

	(include_subdirs qualified)
	(rocq.theory
	  (name skylabs.ltac2.extra.cram.${TEST}) ; logical path of this library
	  (theories
	    Stdlib
	    Ltac2
	    skylabs.ltac2.extra
	   ))

	(include dune.inc)
EOF

    echo ';; DO NOT MODIFY. Generated by ../setup-tests.sh' > dune.inc
    echo >> dune.inc

    find . -name '*.[ch]pp' |
    sort |
    while read i
    do
      ../../tests/cpp2v-dune-gen.sh -p '' -- $i -- -std=c++20 >> dune.inc
    done
    cd ..
done

# vim: set noexpandtab shiftwidth=2:
