find . -maxdepth 2 -name run.t |
while read run
do
  DIR=`dirname $run`
  TEST=`basename $DIR`
  TEST=${TEST%.t}
  echo "Setup $TEST"
  cd $DIR
  rm -f flags
  ln -s ../../../flags .

  cat > dune-project <<-EOF
	(lang dune 3.21)
	(using rocq 0.11)
	;; DO NOT MODIFY. Generated by ../setup-tests.sh
EOF
  cat > dune <<-EOF
	;; DO NOT MODIFY. Generated by ../setup-tests.sh

	(env
	  (_
	    (flags :standard %{read-lines:flags/ocamlc})
	    (ocamlopt_flags :standard -O3 -unbox-closures)
	    (rocq
	     (rocqdep_flags :standard -w +all)
	     (flags (:standard %{read-lines:flags/coqc})))))

	(include_subdirs qualified)
	(rocq.theory
	  (name skylabs.ltac2.logger.cram.${TEST}) ; logical path of this library
	  ; skylabs deps
	  (theories
	    Stdlib
	    Ltac2 skylabs.ltac2.extra
	    skylabs.ltac2.logger))
EOF
done

# vim: set noexpandtab shiftwidth=2:
