(lang dune 3.22)
(using rocq 0.12)
(name rocq-skylabs-brick-cpp-prog)

(generate_opam_files)

(maintainers
 "Paolo Giarrusso <paolo@skylabs-ai.com>"
 "Jan-Oliver Kaiser <janno@skylabs-ai.com>"
 "Simon Hudon <simon@skylabs-ai.com>"
 "Rodolphe Lepigre <rodolphe.lepigre@skylabs-ai.com>")

(authors
 "Gregory Malecha <gregory@skylabs-ai.com>"
 "Paolo Giarrusso <paolo@skylabs-ai.com>"
 "Jan-Oliver Kaiser <janno@skylabs-ai.com>"
 "Simon Hudon <simon@skylabs-ai.com>"
 "Rodolphe Lepigre <rodolphe.lepigre@skylabs-ai.com>")

(license LicenseRef-BedRock)

(source (github SkyLabsAI/BRiCk))

(package
 (name rocq-skylabs-brick-cpp-prog)
 (synopsis "Rocq plugin providin access to BRiCk's cpp2v frontend")
 (depends
  rocq-skylabs-brick
  rocq-skylabs-cpp2v
  rocq-tools))

(subst disabled)
