(lang dune 3.22)
(using rocq 0.12)
(name ltac2-guesstimator)

(generate_opam_files)

(maintainers "Jan-Oliver Kaiser <janno@skylabs-ai.com>")
(authors "Jan-Oliver Kaiser <janno@skylabs-ai.com>")
(license TODO)

(package
 (name ltac2-guesstimator)
 (synopsis "Ltac2 bindings for guesstimator")
 (depends
  (dune (>= 3.22))
  (ocaml (>= 4.08))
  rocq-runtime
  rocq-core
  guesstimator))
