(env
 (sl_timing
  (binaries (../rocq-tools/bin/rocq_perf.exe as rocq))
  (rocq
   (rocqdoc_flags %{read-lines:flags/coqdoc})
   (rocqdoc_header flags/header.html)
   (rocqdoc_footer flags/footer.html)))
 (_
  (rocq
   (rocqdoc_flags %{read-lines:flags/coqdoc})
   (rocqdoc_header flags/header.html)
   (rocqdoc_footer flags/footer.html))))
