(env
 (sl_timing
  (binaries (../rocq-tools/bin/rocq_perf.exe as rocq))
  (flags :standard %{dune-warnings})
  (ocamlopt_flags :standard -O3 -unbox-closures)
  (rocq
   (rocqdep_flags :standard -w +all)
   (flags :standard %{read-lines:flags/coqc})
   (rocqdoc_flags %{read-lines:flags/coqdoc})
   (rocqdoc_header flags/header.html)
   (rocqdoc_footer flags/footer.html)))
 ; Same, but without rocq_perf.
 (_
  (flags :standard %{dune-warnings})
  (ocamlopt_flags :standard -O3 -unbox-closures)
  (rocq
   (rocqdep_flags :standard -w +all)
   (flags :standard %{read-lines:flags/coqc})
   (rocqdoc_flags %{read-lines:flags/coqdoc})
   (rocqdoc_header flags/header.html)
   (rocqdoc_footer flags/footer.html))))
