(lang dune 3.22)
(using rocq 0.12)
(name rocq-attrs)

(generate_opam_files)

(maintainers
 "Gregory Malecha <gregory@skylabs-ai.com>")

(authors
 "Gregory Malecha <gregory@skylabs-ai.com>")

(source (github SkyLabsAI/BRiCk))

(license LGPL-2.1-or-later)

(package
 (name rocq-attrs)
 (synopsis "Rocq attributes for definitions")
 (depends
  rocq-core
  rocq-stdlib))

(subst disabled)
