(lang dune 3.22)
(using rocq 0.12)
(cram enable)
(name guesstimator)

(generate_opam_files)

(maintainers "Jan-Oliver Kaiser <janno@skylabs-ai.com>")
(authors "Jan-Oliver Kaiser <janno@skylabs-ai.com>")
(license TODO)

(package
 (name guesstimator)
 (depends
  (dune (>= 3.22))
  (ocaml (>= 4.08))
  (cmdliner (>= 1.1.0))
  (csv (>= 2.4))))

(package
 (name ltac2-guesstimator)
 (synopsis "Ltac2 bindings for guesstimator")
 (depends
  (dune (>= 3.22))
  (ocaml (>= 4.08))
  rocq-runtime
  rocq-core
  guesstimator))
