(include_subdirs qualified)
(rocq.theory
 (name skylabs.lang.cpp)
 (package rocq-skylabs-brick)
 (plugins rocq-skylabs-brick.plugin)
 (generate_project_file)
 (theories
  skylabs.iris.extra
  Flocq
  Equations
  Equations.Prop
  Equations.Type
  ; transitive dependencies
  Lens Lens.Elpi Ltac2 Stdlib elpi elpi.apps.NES elpi.apps.NES.elpi
  elpi.apps.derive elpi.apps.derive.elpi elpi.apps.locker elpi.apps.locker.elpi
  elpi_elpi iris skylabs.ltac2.extra skylabs.prelude skylabs.upoly stdpp
 ))
